### PR TITLE
1.01 dev

### PR DESCRIPTION
**Pull request by sadnanalmanir**
The new address for redirect: would be http://deliberation.ruleml.org/1.01/exa/RulebaseCompetition2014/OffshoreHoldingsAnalytics.ruleml

### CODE REVIEW

**Comment by greenTara** [comment]
The final state in which the directory is left has three similarly named files
OffshoreHoldingAnalytics.ruleml
OffshoreHoldingsAnalytics.ruleml
OffshoreHoldingsAnalytics.ruleml~
The first is the file with the old name.  The last one is probably an artifact of an editor. Neither of these files should be present in the final state. Please delete these, and commit to your fork - then I can merge this pull request.

Normally when a file is to be renamed, it is best to commit the delete of the old file and the addition of the new file in the same commit, as Git is smart enough to recognize that you changed the name and it keeps the history intact across the renaming. It is too late to do that for this set of commits, but it something that is good to know for the future.

**Comment by sadnanalmanir** [comment]
I think this time I have deleted all unnecessary file as suggested.

**Comment by greenTara** [comment]
I am reopening the pull request in order to merge it.

**Comment by greenTara** [comment]
On 9/8/14 5:49 PM, Sadnan Al Manir wrote:

> I think this time I have deleted all unnecessary file as suggested.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/RuleML/deliberation-ruleml/pull/78#issuecomment-54892830.
> 
> I merged it. Also I add the redirect 
> (https://github.com/RuleML/deliberation-ruleml/blob/1.01/.htaccess). It 
> appears to be working.

Tara

**Comment by sadnanalmanir** [comment]
Yes. I have checked, the redirect is working perfectly. Unfortunately, the
alignment is not the same as it looks in the XML Copy Editor. But I guess,
it looks alright.

Thank you very much Tara.

regards...
sadnan

**Pull request merged**
